name: DNSWatch
options:
  bundleIdPrefix: com.dnswatch
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  DNSWatch:
    type: application
    platform: macOS
    sources:
      - path: DNSWatch/Sources
        type: group
    settings:
      base:
        INFOPLIST_FILE: DNSWatch/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: DNSWatch/Resources/DNSWatch.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.dnswatch.app
        PRODUCT_NAME: DNSWatch
        OTHER_LDFLAGS:
          - -lpcap
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_IDENTITY: "-"
